name: Install Qt Static
description: Install Qt Static on your Github Actions workflows with just one simple action
author: orestonce
branding:
  icon: package
  color: green
inputs:
  dir:
    description: Directory to install Qt
    default: "qt_static_install"
  version:
    description: Version of Qt to install
    default: "Qt5.15.7-Windows-x86-MinGW8.1.0-staticFull-20221104"
runs:
  using: "composite"
  steps:
  - name: Cache Primes
    id: cache_orestonce_install-qt-static
    uses: actions/cache@v3
    with:
      path: ${{ inputs.dir }}
      key: ${{ inputs.version }}-cache_orestonce_install-qt-static
  - name: install Qt static of windows to dir
    if: steps.cache_orestonce_install-qt-static.outputs.cache-hit != 'true'
    shell: powershell
    run: |
      if ( '${{ runner.os }}' -ne 'Windows') {
          echo "invalid runner.os value: ${{ runner.os }}"
          exit -2
      }
      switch ( "${{ inputs.version }}" ) {
            "Qt5.6.3-Windows-x86-MinGW4.9.4-staticFull-20200104" {
              $var_qt_URL = "https://github.com/orestonce/action/releases/download/qt-static5.6.3/Qt5.6.3-Windows-x86-MinGW4.9.4-staticFull-20200104-ManualPatchSslLib.7z"
              $var_mingw_URL = "https://github.com/orestonce/action/releases/download/qt-static5.6.3/i686-4.9.4-release-posix-dwarf-rt_v5-rev0.7z"
              $var_qt_path = "/Qt5.6.3-Windows-x86-MinGW4.9.4-staticFull-20200104/bin"
              $var_mingw_path = "/mingw32/bin"
              break
            }
            "Qt5.15.7-Windows-x86-MinGW8.1.0-staticFull-20221104" {
              $var_qt_URL = "https://github.com/orestonce/action/releases/download/qt5.15.7/Qt5.15.7-Windows-x86-MinGW8.1.0-staticFull-20221104.7z"
              $var_mingw_URL = "https://github.com/orestonce/action/releases/download/qt5.15.7/i686-8.1.0-release-posix-dwarf-rt_v6-rev0.7z"
              $var_qt_path = "/Qt5.15.7-Windows-x86-MinGW8.1.0-staticFull/bin"
              $var_mingw_path = "/mingw32/bin"
              break
            }
            "Qt5.15.7-Windows-x86_64-MinGW8.1.0-staticFull-20221104" {
              $var_qt_URL = "https://github.com/orestonce/action/releases/download/qt5.15.7/Qt5.15.7-Windows-x86_64-MinGW8.1.0-staticFull-20221104.7z"
              $var_mingw_URL = "https://github.com/orestonce/action/releases/download/qt5.15.7/x86_64-8.1.0-release-posix-seh-rt_v6-rev0.7z"
              $var_qt_path = "/Qt5.15.7-Windows-x86_64-MinGW8.1.0-staticFull/bin"
              $var_mingw_path = "/mingw64/bin"
              break
            }
            default {
               echo "invalid version value: ${{ inputs.version }}"
               exit -1
               break
            }
          }
      $var_qt_7z = $var_qt_URL.Substring($var_qt_URL.lastIndexOf('/')+1)
      $var_mingw_7z = $var_mingw_URL.Substring($var_mingw_URL.lastIndexOf('/')+1)
      
      New-Item -ItemType Directory -Force -Path ${{ inputs.dir }}
      cd ${{ inputs.dir }}
      Invoke-WebRequest -URI $var_qt_URL    -OutFile $var_qt_7z
      Invoke-WebRequest -URI $var_mingw_URL -OutFile $var_mingw_7z
      
      
      7z x $var_qt_7z
      7z x $var_mingw_7z
      if ( '$($var_qt_path)' -ne 'qt_install') {
          move '$($var_qt_path)' qt_install
      }
      if ( '$($var_mingw_path)' -ne 'mingw_install') {
          move '$($var_mingw_path)' mingw_install
      }
    - name: setup Qt env
    shell: powershell
    run: |
      pwd
      cd cd ${{ inputs.dir }}
      Add-Content $env:GITHUB_PATH "${PWD}/qt_install"
      Add-Content $env:GITHUB_PATH "${PWD}/mingw_install"
      if ( '${{ inputs.version }}' -eq 'Qt5.6.3-Windows-x86-MinGW4.9.4-staticFull-20200104') {
          echo "run QQtPatcher.exe"
          .\qt_install\Qt5.6.3-Windows-x86-MinGW4.9.4-staticFull-20200104\QQtPatcher.exe
      }
