name: Install Qt static library
description: Install Qt Static library for static link
author: L-Super
branding:
  icon: package
  color: green
inputs:
  dir:
    description: Directory to install Qt
    default: "Qt_static"
  version:
    description: Version of Qt to install
    default: "Qt6.7.1-Windows-MinGW13.2.0"
runs:
  using: "composite"
  steps:
  - name: Cache Primes
    id: cache-install-qt-static
    uses: actions/cache@v3
    with:
      path: ${{ inputs.dir }}
      key: ${{ inputs.version }}-cache-qt-static
  - name: install Qt static of windows to dir
    if: steps.cache-install-qt-static.outputs.cache-hit != 'true'
    shell: powershell
    run: |
      if ( '${{ runner.os }}' -ne 'Windows') {
          echo "invalid runner.os value: ${{ runner.os }}"
          exit -2
      }
      switch ( "${{ inputs.version }}" ) {
            "Qt6.7.1-Windows-MinGW13.2.0" {
              $var_qt_URL = "https://github.com/L-Super/FramelessWindow/releases/download/v1.0.0/Qt6.7.1-Windows-MinGW13.2.0.7z"
              $var_mingw_URL = "https://github.com/L-Super/FramelessWindow/releases/download/v1.0.0/mingw64-13.2.0.7z"
              $var_qt_dir_name = "Qt6.7.1-Windows-MinGW13.2.0"
              $var_mingw_dir_name = "mingw64"
              break
            }
            "Qt5.15.7-Windows-x86_64-MinGW8.1.0-staticFull-20221104" {
              $var_qt_URL = "https://github.com/orestonce/action/releases/download/qt5.15.7/Qt5.15.7-Windows-x86_64-MinGW8.1.0-staticFull-20221104.7z"
              $var_mingw_URL = "https://github.com/orestonce/action/releases/download/qt5.15.7/x86_64-8.1.0-release-posix-seh-rt_v6-rev0.7z"
              $var_qt_dir_name = "Qt5.15.7-Windows-x86_64-MinGW8.1.0-staticFull"
              $var_mingw_dir_name = "mingw64"
              break
            }
            default {
               echo "invalid version value: ${{ inputs.version }}"
               exit -1
               break
            }
          }
      $var_qt_7z = $var_qt_URL.Substring($var_qt_URL.lastIndexOf('/') + 1)
      $var_mingw_7z = $var_mingw_URL.Substring($var_mingw_URL.lastIndexOf('/') + 1)
      
      New-Item -ItemType Directory -Force -Path ${{ inputs.dir }}
      cd ${{ inputs.dir }}
      Invoke-WebRequest -URI $var_qt_URL    -OutFile $var_qt_7z
      Invoke-WebRequest -URI $var_mingw_URL -OutFile $var_mingw_7z
      
      7z x $var_qt_7z
      7z x $var_mingw_7z
      
      Remove-Item -Recurse -Force $var_qt_7z
      Remove-Item -Recurse -Force $var_mingw_7z
      
      if ( $var_qt_dir_name -ne 'Qt') {
          move $var_qt_dir_name Qt
      }
      if ( $var_mingw_dir_name -ne 'MinGW') {
          move $var_mingw_dir_name MinGW
      }
  - name: setup Qt env
    shell: powershell
    run: |
      cd ${{ inputs.dir }}
      Add-Content $env:GITHUB_PATH "${PWD}\Qt\bin"
      Add-Content $env:GITHUB_PATH "${PWD}\MinGW\bin"
