name: Install Qt Static
description: Install Qt Static on your Github Actions workflows with just one simple action
author: orestonce
branding:
  icon: package
  color: green
inputs:
  dir:
    description: Directory to install Qt
    default: "qt-static"
  version:
    description: Version of Qt to install
    default: "5.6.3_windows"
runs:
  using: "composite"
  steps:
  - name: Setup and run action
    shell: powershell
    if: $${{ runner.os == 'Windows' && inputs.version == '5.6.3_windows' }}
    run: |
      New-Item -ItemType Directory -Force -Path ${{ inputs.dir }}
      cd ${{ inputs.dir }}
      curl -L https://github.com/orestonce/action/releases/download/qt-static5.6.3/Qt5.6.3-Windows-x86-MinGW4.9.4-staticFull-20200104-ManualPatchSslLib.7z -o Qt5.6.3-Windows-x86-MinGW4.9.4-staticFull-20200104-ManualPatchSslLib.7z
      curl -L https://github.com/orestonce/action/releases/download/qt-static5.6.3/i686-4.9.4-release-posix-dwarf-rt_v5-rev0.7z -o i686-4.9.4-release-posix-dwarf-rt_v5-rev0.7z
      7z x download/Qt5.6.3-Windows-x86-MinGW4.9.4-staticFull-20200104-ManualPatchSslLib.7z
      7z x download/i686-4.9.4-release-posix-dwarf-rt_v5-rev0.7z
      dir
      #echo "" >> $GITHUB_PATH
      #go run install-qt-static.go -dir ${{ inputs.dir }} -version ${{ inputs.version }}

