name: Install Qt Static
description: Install Qt Static on your Github Actions workflows with just one simple action
author: orestonce
branding:
  icon: package
  color: green
inputs:
  dir:
    description: Directory to install Qt
    default: "qt_static_install"
  version:
    description: Version of Qt to install
    default: "Qt5.15.7-Windows-x86-MinGW8.1.0-staticFull-20221104"
runs:
  using: "composite"
  steps:
  - name: install Qt static of windows
    shell: powershell
    run: |
      switch ( "${{ inputs.version }}" ) {
            "Qt5.6.3-Windows-x86-MinGW4.9.4-staticFull-20200104" {
              $var_qt_URL = "https://github.com/orestonce/action/releases/download/qt-static5.6.3/Qt5.6.3-Windows-x86-MinGW4.9.4-staticFull-20200104-ManualPatchSslLib.7z"
              $var_mingw_URL = "https://github.com/orestonce/action/releases/download/qt-static5.6.3/i686-4.9.4-release-posix-dwarf-rt_v5-rev0.7z"
              $var_qt_path = "/Qt5.6.3-Windows-x86-MinGW4.9.4-staticFull-20200104/bin"
              $var_mingw_path = "/mingw32/bin"
              break
            }
            "Qt5.15.7-Windows-x86-MinGW8.1.0-staticFull-20221104" {
              $var_qt_URL = "https://github.com/orestonce/action/releases/download/qt5.15.7/Qt5.15.7-Windows-x86-MinGW8.1.0-staticFull-20221104.7z"
              $var_mingw_URL = "https://github.com/orestonce/action/releases/download/qt5.15.7/i686-8.1.0-release-posix-dwarf-rt_v6-rev0.7z"
              $var_qt_path = "/Qt5.15.7-Windows-x86-MinGW8.1.0-staticFull/bin"
              $var_mingw_path = "/mingw32/bin"
              break
            }
            "Qt5.15.7-Windows-x86_64-MinGW8.1.0-staticFull-20221104" {
              $var_qt_URL = "https://github.com/orestonce/action/releases/download/qt5.15.7/Qt5.15.7-Windows-x86_64-MinGW8.1.0-staticFull-20221104.7z"
              $var_mingw_URL = "https://github.com/orestonce/action/releases/download/qt5.15.7/x86_64-8.1.0-release-posix-seh-rt_v6-rev0.7z"
              $var_qt_path = "/Qt5.15.7-Windows-x86_64-MinGW8.1.0-staticFull/bin"
              $var_mingw_path = "/mingw64/bin"
              break
            }
            default {
               echo "invalid version value: ${{ inputs.version }}"
               exit -1
               break
            }
          }
      $var_mingw_7z = $var_mingw_URL.Substring($var_mingw_URL.lastIndexOf('/')+1)
      $var_qt_7z = $var_qt_URL.Substring($var_qt_URL.lastIndexOf('/')+1)
      
      New-Item -ItemType Directory -Force -Path ${{ inputs.dir }}
      cd ${{ inputs.dir }}
      Invoke-WebRequest -URI $var_qt_URL    -OutFile $var_qt_7z
      Invoke-WebRequest -URI $var_mingw_URL -OutFile $
      
      
      7z x $var_qt_7z
      7z x $var_mingw_7z
      Add-Content $env:GITHUB_PATH "${PWD}$($var_qt_path)"
      Add-Content $env:GITHUB_PATH "${PWD}$($var_mingw_path)"
